create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  username text not null,
  name text not null,
  photo text,
  items jsonb not null default '[]'::jsonb,
  planner_events jsonb not null default '[]'::jsonb,
  schedule_url text,
  schedule_image text,
  notifications jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists planner_events jsonb not null default '[]'::jsonb;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "Users can manage their own push subscriptions" on public.push_subscriptions;
create policy "Users can manage their own push subscriptions"
  on public.push_subscriptions for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.sent_reminders (
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  reminder_date date not null,
  reminder_time time not null,
  primary key (user_id, item_id, reminder_date, reminder_time)
);

create table if not exists public.active_account_sessions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  session_id uuid not null,
  last_seen timestamptz not null default now(),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.active_account_sessions enable row level security;

create or replace function public.claim_account_session(p_session_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed_session uuid;
begin
  if auth.uid() is null then
    return false;
  end if;

  insert into public.active_account_sessions (user_id, session_id, last_seen, expires_at)
  values (auth.uid(), p_session_id, now(), now() + interval '2 minutes')
  on conflict (user_id) do update
    set session_id = excluded.session_id,
        last_seen = now(),
        expires_at = now() + interval '2 minutes'
    where active_account_sessions.session_id = p_session_id
       or active_account_sessions.expires_at <= now()
  returning session_id into claimed_session;

  return claimed_session = p_session_id;
end;
$$;

create or replace function public.release_account_session(p_session_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.active_account_sessions
  where user_id = auth.uid() and session_id = p_session_id;
$$;

grant execute on function public.claim_account_session(uuid) to authenticated;
grant execute on function public.release_account_session(uuid) to authenticated;

notify pgrst, 'reload schema';

alter table public.sent_reminders enable row level security;

drop policy if exists "Users can read their own sent reminders" on public.sent_reminders;
create policy "Users can read their own sent reminders"
  on public.sent_reminders for select
  using (auth.uid() = user_id);

alter table public.profiles enable row level security;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, username, name, items, notifications)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1), 'user'),
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1), 'User'),
    '[]'::jsonb,
    '[]'::jsonb
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
